# 
# PGM
# The original PvP Game Manager for Minecraft.

map:
  folders:
  - default
  - maps/
  repositories:
  - uri: https://github.com/PGMDev/Maps
    path: default-maps
  pools: map-pools.yml
restart:
  uptime: -1
  match-limit: -1
join:
  priority-kick: true
  min-players: 2
  anytime: true
  limit: true
  balance: true
motd: "{2}» &b{1} {2}«"
experiments:
  match-preload-seconds: 3
  match-destroy-seconds: 10
  match-teleports-per-second: 10
  tab-render-ticks: 10
  unload-non-match-worlds: true
sidebar:
  header: ''
  footer: ''
countdown:
  start: 30s
  huddle: 0s
  cycle: 15s
ui:
  proximity: false
  tablist: true
  sidebar: true
  participants-see-observers: true
  fireworks: true
tablist:
  left: "&bplay.sgcraft.net"
  right: "&bplay.sgcraft.net"
gameplay:
  refill-wool: true
groups:
  founder:
    prefix: '&2&lFOUNDER '
    permission:
    - +cmi.command.staffmsg
    - -pgm.group.admin
    - -pgm.group.chief
    - -pgm.group.snrmod
    - -pgm.group.mod
    - -pgm.group.jrmod
    - -pgm.group.trainee
  admin:
    prefix: '&c&lADMIN '
    permission:
    - +cmi.command.staffmsg
    - -pgm.group.chief
    - -pgm.group.snrmod
    - -pgm.group.mod
    - -pgm.group.jrmod
    - -pgm.group.trainee
  chief:
    prefix: '&6&lCHIEF '
    permission:
    - +cmi.command.staffmsg
    - -pgm.group.snrmod
    - -pgm.group.mod
    - -pgm.group.jrmod
    - -pgm.group.trainee
  snrmod:
    prefix: '&e&lSNR '
    permission:
    - +cmi.command.staffmsg
    - -pgm.group.mod
    - -pgm.group.jrmod
    - -pgm.group.trainee
  mod:
    prefix: '&9&lMOD '
    permission:
    - +cmi.command.staffmsg
    - -pgm.group.jrmod
    - -pgm.group.trainee
  jrmod:
    prefix: '&b&lJR '
    permission:
    - +cmi.command.staffmsg
    - -pgm.group.trainee
  trainee:
    prefix: '&3&lTRAINEE '
    permission:
    - +cmi.command.staffmsg
  dragonplus:
    prefix: '&c&l✯&f+'
  dragon:
    prefix: '&c✯'
  wyvern:
    prefix: '&5✯'
  serpent:
    prefix: '&2✯'
  default:
    permissions:
    - -bukkit.command.kill
    - -bukkit.command.me
    - -bukkit.command.tell
    - -worldedit.navigation.ceiling
    - -worldedit.navigation.up
    - -worldedit.calc
    - -commandbook.pong
    - -commandbook.speed.flight
    - -commandbook.speed.walk
    - +cmi.command.server
    - +cmi.command
    observer-permissions:
    - +worldedit.navigation.*
    - +commandbook.teleport
    participant-permissions:
    - -worldedit.navigation.thru.tool
    - -worldedit.navigation.jumpto.tool
    - -commandbook.teleport
community:
  server-name: SGCraft
  rules-link: Read the rules at https://discord.sgcraft.net/
  appeal-msg: Appeal at https://discord.sgcraft.net/
  enabled: false