name: Mercury
softdepend: [ViaVersion, PlaceholderAPI]
description: ${project.parent.description}
main: ${project.mainClass}
version: ${project.version} (git-${git.commit.id.abbrev})
website: ${project.parent.url}
